### ISSUE TITLE
Moving certificates doesn't trigger watch

### ISSUE THREAD

**Issue by jamielennox** [cloudflare/certinel#12]
When replacing certificates I'm not writing to an existing file, i've got the new certificates and then i basically copy them into place. In fswatch this is causing a `REMOVE` event and a `CREATED` event, neither of which are handled by certinel https://github.com/cloudflare/certinel/blob/cb169af03858e287e570039166f7ba2ba30629c5/fswatcher/fswatcher.go#L61

The `REMOVE` event is a bit difficult, but i think that at least `CREATED` should be handled here and cause a reload.

**Comment by jamielennox** [comment]
I basically copied the code i needed rather than fork the library. So my main usage here is reloading certificates in kubernetes when the secret changes. In that case there are multiple levels of symlinking in place that are not supported from fsnotify/fsnotify#199.

You can merge the PR or not, but even this fix isn't going to work for me.

**Comment by jamielennox** [comment]
just to finish this up, it looks like you can do it by handling Remove. This works in my test, https://martensson.io/go-fsnotify-and-kubernetes-configmaps/

**Comment by terinjokes** [comment]
At some point GitHub removed my watches from this repository. I'll take a look.
