### ISSUE TITLE
Watch doesn't watch key file

### ISSUE THREAD

**Issue by jamielennox** [cloudflare/certinel#14]
I'm not sure how big a deal this would be in practice, however in my testing to see if this is working i'm regenerating a new certificate and a new key together and moving them into place. Mostly you don't refresh a key in production, but there would be times. 

If not supported, maybe a disclaimer? The fact that i pass both cert and key to Watcher made me think the key was being watched as well. 

It's actually a little bit difficult to support because if you change both key and cert together like I am then each watch triggers the reload operation and the key and certificate will not match so you need to be able to ignore the errors until both files are in place together.

**Comment by terinjokes** [comment]
Our internal tool for issuing and renewing certificates for services did not support rotating keys, only certificates. However, I think the `fswatcher` code should also watch that file. I'll look at adding that this week.
